import type { PlaceWithLatestReading } from '@veevalve/core';

export const mobileMockPlaces: PlaceWithLatestReading[] = [
  {
    id: 'pirita-beach',
    externalId: 'pirita-beach',
    nameEt: 'Pirita rand',
    nameEn: 'Pirita Beach',
    type: 'BEACH',
    municipality: 'Tallinn',
    addressEt: 'Merivälja tee 1, Tallinn',
    addressEn: 'Merivälja tee 1, Tallinn',
    latitude: 59.4697,
    longitude: 24.8405,
    latestReading: {
      id: 'pirita-reading-1',
      placeId: 'pirita-beach',
      sampledAt: '2026-02-15T09:00:00.000Z',
      status: 'GOOD',
      statusReasonEt: 'Suplusvesi vastab nõuetele.',
      statusReasonEn: 'Water quality meets requirements.',
      source: 'TERVISEAMET_XML',
      sourceUrl: 'https://vtiav.sm.ee/index.php/?active_tab_id=A',
    },
  },
  {
    id: 'haabneeme-beach',
    externalId: 'haabneeme-beach',
    nameEt: 'Haabneeme rand',
    nameEn: 'Haabneeme Beach',
    type: 'BEACH',
    municipality: 'Viimsi',
    addressEt: 'Randvere tee 2, Viimsi',
    addressEn: 'Randvere tee 2, Viimsi',
    latitude: 59.5118,
    longitude: 24.8261,
    latestReading: {
      id: 'haabneeme-reading-1',
      placeId: 'haabneeme-beach',
      sampledAt: '2026-02-15T09:00:00.000Z',
      status: 'BAD',
      statusReasonEt: 'Bakterioloogiline näit ületab normi.',
      statusReasonEn: 'Bacteriological measurement above threshold.',
      source: 'TERVISEAMET_XML',
      sourceUrl: 'https://vtiav.sm.ee/index.php/?active_tab_id=A',
    },
  },
  {
    id: 'kalev-spa',
    externalId: 'kalev-spa',
    nameEt: 'Kalev Spa bassein',
    nameEn: 'Kalev Spa Pool',
    type: 'POOL',
    municipality: 'Tallinn',
    addressEt: 'Aia 18, Tallinn',
    addressEn: 'Aia 18, Tallinn',
    latitude: 59.4404,
    longitude: 24.7525,
    latestReading: {
      id: 'kalev-reading-1',
      placeId: 'kalev-spa',
      sampledAt: '2026-02-15T09:00:00.000Z',
      status: 'GOOD',
      statusReasonEt: 'Vesi on korras.',
      statusReasonEn: 'Water quality is compliant.',
      source: 'TERVISEAMET_XML',
      sourceUrl: 'https://vtiav.sm.ee/index.php/?active_tab_id=A',
    },
  },
];
